name: Delete package versions
description: delete version of packages on GitHub packages
author: "Wherobots"

branding:
  color: "red"
  icon: "delete"

inputs:
  owner:
    description: 'Owner of the repo containing the package version to delete. Defaults to the owner of the repo running the action.'
    required: false
  package_type:
    description: 'Package type, could be maven or npm'
    required: true
  packages:
    description: 'GitHub package names to delete versions from, separated by comma'
    required: true
  versions:
    description: 'Package versions to delete, separated by comma'
    required: true
  github_token:
    description: 'A GitHub token with delete access to packages.'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/main.js'
